import './globals.css'
import { Source_Sans_3 } from 'next/font/google'

const source = Source_Sans_3({subsets:['latin'],
weight: ['400','300','200','600']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="pl">
      
      <body className={source.className}>
        {children}
      </body>
    </html>
  )
}
